<?xml version="1.0" encoding="UTF-8" ?>

<!-- Esercizio: 
- root: TEI 

- Figli: 
    header (obbligatorio una volta sola) 
    facsimile (opzionale una volta sola - ?) 
    testo (obbligatorio una o più volte - +) 
* testo è un mixed content con possibile elemento 

Attributi: 
    header: type:(fixed, CDATA “intestazione”); lang(opzionale, NMTOKEN) 
    facsimile: source:(obbligatorio); ref(opzionale, IDREFS) 
    testo: id(obbligatorio, ID) type(opzionale contenuto testuale) -->

<!DOCTYPE TEI [
<!ELEMENT TEI (header,facsimile?,text+) >

<!ELEMENT header (#PCDATA) >
<!ATTLIST header type CDATA #FIXED "intestazione" >
<!ATTLIST header lang NMTOKEN #IMPLIED >

<!ELEMENT facsimile (#PCDATA) >
<!ATTLIST facsimile source CDATA #REQUIRED >
<!ATTLIST facsimile ref IDREFS #IMPLIED >

<!ELEMENT text (#PCDATA|segmento)* >
<!ATTLIST text id ID #REQUIRED >
<!ATTLIST text type CDATA #IMPLIED >

<!ELEMENT segmento (#PCDATA) >
]>

<TEI>

    <header></header>

    <facsimile source="src"></facsimile>

    <text id="utente"> <segmento> testo </segmento> </text>

</TEI>